# Connection
listen_addresses = '*'
port = 5432

# Memory
shared_buffers = 512MB
work_mem = 64MB
maintenance_work_mem = 256MB

# Query Planner
random_page_cost = 1.1
effective_cache_size = 2GB

# Logging
log_min_duration_statement = 100
log_line_prefix = '%t [%p]: '
log_statement = 'none'
